logo: /images/avatar.gif
han_type: zh-Hant
menu:
  首页: /
  归档: /pigeonhole
  链接: /links
  关于: /about
# disqus:
# short_name: YOUR_DUOSHUO_ID
icon:
  rss: https://whitealco.github.io/atom.xml
  twitter: white_Alcoholer
  github: whitealco
  weibo: 5651204420
  zhihu: dou-huang-81
